spring.application.name=pineaple
# Local development
spring.datasource.url=jdbc:postgresql://localhost:5432/pineapple
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080